# ----------------------------------------
# DATABASE & CONNECTION POOL (HikariCP)
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME}?reWriteBatchedInserts=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Otimizações de recursos para VPS/Docker
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=20000

# ----------------------------------------
# JPA & HIBERNATE
# ----------------------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Segurança: Nunca altere a estrutura do banco automaticamente em produção
spring.jpa.hibernate.ddl-auto=validate

# Performance: Desligue os logs de SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ----------------------------------------
# SECURITY & CORS
# ----------------------------------------
api.security.token.secret=${PASSWORD_TOKEN_JWT}
api.security.cors.allowed-origins=${CORS_ORIGINS}